{% set name = "vsgImGui" %}
{% set version = "0.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - url: https://github.com/vsg-dev/vsgImGui/archive/v{{ version }}.tar.gz
    sha256: 016191dfa4953fd381990166cf7df6f1328ced02411afcc7387e9121bf825d92
    patches:
      - patches/0001-Add-options-to-use-system-dependencies.patch
      - patches/0003-Find-imgui-and-implot-in-package-config-when-system-.patch

build:
  number: 0
  run_exports:
    - {{ pin_subpackage('vsgimgui', max_pin='x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - cmake
    - ninja  # [not win]
    - pkgconfig  # [linux]
  host:
    - imgui
    - implot
    - libvulkan-headers
    - libvulkan-loader
    - vulkanscenegraph
  run:
    - libvulkan-loader
    - vulkanscenegraph

test:
  commands:
    - test -f $PREFIX/include/vsgImGui/Export.h  # [not win]
    - test -f $PREFIX/lib/libvsgImGui${SHLIB_EXT}  # [not win]
    - test -f $PREFIX/lib/cmake/vsgImGui/vsgImGuiConfig.cmake  # [not win]
    - if not exist %PREFIX%\\Library\\include\\vsgImGui\\Export.h exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\vsgImGui.lib exit 1  # [win]
    - if not exist %PREFIX%\\Library\\bin\\vsgImGui.dll exit 1  # [win]
    - if not exist %PREFIX%\\Library\\lib\\cmake\\vsgImGui\\vsgImGuiConfig.cmake exit 1  # [win]
  requires:
    - {{ compiler("c") }}
    - {{ compiler("cxx") }}
    - cmake
    - ninja  # [not win]
    - pkgconfig  # [linux]
    - vsgXchange
  files:
    - tests/

about:
  home: https://vsg-dev.github.io/vsg-dev.io/
  summary: Integration of VulkanSceneGraph with ImGui
  license: MIT
  license_file: LICENSE.md
  dev_url: https://github.com/vsg-dev/vsgImGui

extra:
  recipe-maintainers:
    - jeongseok-meta
